export const siteConfig = {
  name: "saad.sh",
  url: "https://saad.sh",
  description: "Writing about TypeScript, AI tooling, web development, etc.",
  locale: "en_US",
  language: "en-US",
  titleTemplate: "%s | saad.sh",
  twitterCard: "summary_large_image",
  author: {
    name: "Saad Bash",
    url: "https://saad.sh",
    occupation: "Software Engineer",
    email: "saadbashdev@gmail.com",
    linkedin: "https://www.linkedin.com/in/saadbash",
    github: "https://github.com/saadjs",
    avatar: "/static/images/avatar.png",
  },
  github: {
    editPostBaseUrl: "https://github.com/saadjs/saad-sh/edit/main/content/posts",
    sourceUrl: "https://github.com/saadjs/saad-sh",
  },
  nav: [
    { label: "Tags", href: "/tags" },
    { label: "About", href: "/about" },
  ],
  header: {
    tagline: "",
  },
  routes: {
    posts: "/",
    about: "/about",
    tags: "/tags",
    feed: "/feed.xml",
    sitemap: "/sitemap.xml",
  },
  robots: {
    index: true,
    follow: true,
  },
  footer: {
    eyebrow: "saad.sh",
    description: "Personal blog for software notes, patterns, and experiments.",
    links: {
      feed: "RSS",
      source: "Source",
      github: "GitHub",
      linkedin: "LinkedIn",
    },
    copyrightOwner: "saad.sh",
    copyrightSuffix: "All rights reserved.",
  },
  homePage: {
    eyebrow: "Personal blog",
    heading: "Software Development.",
    emptyMessage: "No posts yet.",
    postsEyebrow: "Recent posts",
    postsHeading: "Latest writing",
    postsCountLabel: (count: number) => `${count} published`,
  },
  tagsPage: {
    title: "Tags",
    description: "Browse all tags",
    heading: "Tags",
    emptyMessage: "No tags yet.",
    eyebrow: "Tag index",
    intro: "Explore posts by topic.",
    countLabel: (count: number) => `${count} ${count === 1 ? "post" : "posts"}`,
  },
  aboutPage: {
    title: "About",
    description: "Learn more about Saad Bash.",
    kicker: "About the author",
  },
  postPage: {
    tagsLabel: "Filed under",
    editLabel: "Edit on GitHub",
    relatedPostsHeading: "Related posts",
  },
  tagPage: {
    title: (tag: string) => `Posts tagged "${tag}"`,
    description: (tag: string) => `All posts tagged with ${tag}`,
    heading: (tag: string) => `Posts tagged "${tag}"`,
    eyebrow: "Filtered archive",
    summary: (count: number) =>
      `${count} ${count === 1 ? "post" : "posts"} filed under this topic.`,
  },
  sitemap: {
    changeFrequency: {
      about: "monthly",
      home: "weekly",
      tagsIndex: "weekly",
      tag: "weekly",
      post: "monthly",
    },
    priority: {
      about: 0.7,
      home: 1,
      tagsIndex: 0.6,
      tag: 0.5,
      post: 0.8,
    },
  },
} as const;
