export const siteConfig = {
  name: "saad.sh",
  url: "https://saad.sh",
  description: "Writing about TypeScript, AI tooling, web development, etc.",
  locale: "en_US",
  language: "en-US",
  titleTemplate: "%s | saad.sh",
  twitterCard: "summary_large_image",
  author: {
    name: "Saad Bash",
    url: "https://saad.sh",
    occupation: "Software Engineer",
    email: "saadbashdev@gmail.com",
    linkedin: "https://www.linkedin.com/in/saadbash",
    github: "https://github.com/saadjs",
    avatar: "/static/images/avatar.png",
  },
  github: {
    editPostBaseUrl: "https://github.com/saadjs/saad-sh/edit/main/src/content/posts",
    sourceUrl: "https://github.com/saadjs/saad-sh",
  },
  nav: [
    { label: "Posts", href: "/posts" },
    { label: "Projects", href: "/projects" },
    { label: "Tags", href: "/tags" },
    { label: "Newsletter", href: "/newsletter" },
    { label: "About", href: "/about" },
  ],
  header: {
    tagline: "",
  },
  routes: {
    home: "/",
    posts: "/posts",
    projects: "/projects",
    about: "/about",
    tags: "/tags",
    newsletter: "/newsletter",
    feed: "/feed.xml",
    sitemap: "/sitemap.xml",
  },
  alternateTypes: {
    "application/rss+xml": "/feed.xml",
  },
  robots: {
    index: true,
    follow: true,
  },
  footer: {
    eyebrow: "saad.sh",
    description: "Personal blog for software notes, patterns, and experiments.",
    links: {
      feed: "RSS",
      source: "Source",
      github: "GitHub",
      linkedin: "LinkedIn",
    },
    copyrightOwner: "saad.sh",
    copyrightSuffix: "All rights reserved.",
  },
  homePage: {
    eyebrow: "Personal blog",
    heading: "Software Development.",
    emptyMessage: "No posts yet.",
    postsEyebrow: "Recent posts",
    postsHeading: "Latest writing",
    postsCountLabel: (count: number) => `${count} published`,
    postsLimit: 10,
    allPostsLabel: "See all posts",
  },
  postsPage: {
    title: "Posts",
    description: "Every post on saad.sh, newest first.",
    heading: "All posts",
    eyebrow: "Archive",
    intro: "Everything I have written, newest first.",
    emptyMessage: "No posts yet.",
    countLabel: (count: number) => `${count} ${count === 1 ? "post" : "posts"}`,
  },
  tagsPage: {
    title: "Tags",
    description: "Browse all tags",
    heading: "Tags",
    emptyMessage: "No tags yet.",
    eyebrow: "Tag index",
    intro: "Explore posts by topic.",
    countLabel: (count: number) => `${count} ${count === 1 ? "post" : "posts"}`,
  },
  aboutPage: {
    title: "About",
    description: "Learn more about Saad Bash.",
    kicker: "About the author",
  },
  projectsPage: {
    title: "Projects",
    description: "Side projects and recent things built by Saad Bash.",
    heading: "Projects",
    eyebrow: "Side projects",
    intro: "A few things I have built/been building lately.",
  },
  postPage: {
    tagsLabel: "Filed under",
    editLabel: "Edit on GitHub",
    relatedPostsHeading: "Related posts",
    tocLabel: "On this page",
  },
  tagPage: {
    title: (tag: string) => `Posts tagged "${tag}"`,
    description: (tag: string) => `All posts tagged with ${tag}`,
    heading: (tag: string) => `Posts tagged "${tag}"`,
    eyebrow: "Filtered archive",
    summary: (count: number) =>
      `${count} ${count === 1 ? "post" : "posts"} filed under this topic.`,
  },
  newsletter: {
    eyebrow: "Newsletter",
    heading: "Subscribe",
    description:
      "Notes from building, AI stuff, and what I learned along the way. No fixed schedule, it goes out when there is something worth sending. No spam, unsubscribe anytime.",
    emailPlaceholder: "you@example.com",
    buttonLabel: "Subscribe",
    submittingLabel: "Subscribing…",
    successMessage: "Almost there. Check your inbox to confirm your subscription.",
    errorMessage: "Something went wrong. Please try again.",
    invalidEmailMessage: "Please enter a valid email address.",
    from: "Saad Bash <newsletter@updates.saad.sh>",
    replyTo: "saadbashdev@gmail.com",
    confirmSubject: "Confirm your subscription to saad.sh",
    // Owner-facing signup notification. Separate sender from the newsletter
    // itself so these can be filtered without touching subscriber mail.
    notifications: {
      to: "saadbashdev@gmail.com",
      from: "saad.sh <notify@updates.saad.sh>",
    },
    emailLogo: "/android-chrome-192x192.png",
    page: {
      title: "Newsletter",
      description: "Occasional notes on software, AI tooling, and things worth sharing.",
    },
    turnstileSiteKey: "0x4AAAAAAD4khxxVYygRgcEw",
    confirmPage: {
      title: "Confirm subscription",
      heading: "Confirm your subscription",
      description: (email: string) => `Subscribe ${email} to the saad.sh newsletter.`,
      confirmButtonLabel: "Confirm subscription",
      confirmingLabel: "Confirming…",
      confirmingHeading: "Confirming your subscription…",
      confirmingMessage: (email: string) => `Finishing sign-up for ${email}. This takes a second.`,
      noscriptMessage:
        "JavaScript is required to finish confirming. Enable it and reload this page, or reply to the confirmation email and I'll add you manually.",
      successHeading: "You're subscribed!",
      successMessage:
        "Thanks for subscribing. The next letter will land in your inbox. Every email has an unsubscribe link, and you can opt out any time.",
      alreadyMemberHeading: "You're already a member",
      alreadyMemberMessage: "Thanks for being a subscriber, no need to confirm again.",
      invalidHeading: "This link isn't valid",
      invalidMessage: "The confirmation link is invalid or has already been used.",
      expiredHeading: "This link has expired",
      expiredMessage: "Confirmation links are valid for 48 hours. Sign up again to get a new one.",
      errorMessage: "Something went wrong confirming your subscription. Please try again.",
    },
  },
  sitemap: {
    changeFrequency: {
      about: "monthly",
      home: "weekly",
      postsIndex: "weekly",
      projects: "monthly",
      newsletter: "yearly",
      tagsIndex: "weekly",
      tag: "weekly",
      post: "monthly",
    },
    priority: {
      about: 0.7,
      home: 1,
      postsIndex: 0.9,
      projects: 0.75,
      newsletter: 0.6,
      tagsIndex: 0.6,
      tag: 0.5,
      post: 0.8,
    },
  },
} as const;
